### ISSUE TITLE
How to setup the API keys?

### ISSUE THREAD

**Issue by afshinm** [hrr20-over9000/9001#173]
First of all, thanks for this cool project.

Sorry for this question, haven't found anything in the documentation related to this.

I'd like to setup the server for myself but I'm not sure if I need any API key from the vendors? e.g. Soundcloud or Spotify.  As far as I'm aware, the API access to read the songs is not free to use.

**Comment by stefanruijsenaars** [comment]
Thanks! Yes, you'll need to get API keys from the vendors and put them in the superSecretKeys.ts file. We'll update the documentation to reflect this.
